export const translations = {
    en: {
        title: 'App Market',
        subtitle: 'Discover and purchase our premium applications built with cutting-edge technology and proven methodologies.',
        searchPlaceholder: 'Search apps, features...',
        filter: 'Filter:',
        allApps: 'All Apps',
        productivity: 'Productivity',
        analytics: 'Analytics',
        ecommerce: 'E-commerce',
        healthcare: 'Healthcare',
        finance: 'Finance',
        education: 'Education',
        addToCart: 'Add to Cart',
        buyNow: 'Buy Now',
        viewDemo: 'View Demo',
        features: 'Features',
        downloads: 'Downloads',
        rating: 'Rating',
        price: 'Price',
        category: 'Category',
        noApps: 'No apps found matching your criteria.',
        ctaTitle: 'Need a Custom Solution?',
        ctaSubtitle: 'Can\'t find what you need? Request a custom app tailored to your business.',
        getCustomQuote: 'Get Custom Quote',
        viewAllServices: 'View All Services',
        cart: 'Cart',
        items: 'items',
        total: 'Total',
        checkout: 'Checkout',
        freeTrialAvailable: 'Free Trial',
        monthlySubscription: 'Monthly Subscription',
        oneTimePurchase: 'One-Time Purchase'
    }
};

export const categories = [
    { id: 'all', label: 'All Apps', count: 12 },
    { id: 'productivity', label: 'Productivity', count: 4 },
    { id: 'analytics', label: 'Analytics', count: 3 },
    { id: 'ecommerce', label: 'E-commerce', count: 2 },
    { id: 'healthcare', label: 'Healthcare', count: 1 },
    { id: 'finance', label: 'Finance', count: 1 },
    { id: 'education', label: 'Education', count: 1 }
];

export const apps = [
    {
        id: 1,
        name: 'TaskFlow Pro',
        category: 'productivity',
        description: 'Advanced project management and team collaboration platform with AI-powered insights.',
        image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 49.99,
        originalPrice: 79.99,
        rating: 4.8,
        downloads: '25K+',
        features: [
            'AI-powered task prioritization',
            'Real-time team collaboration',
            'Advanced analytics dashboard',
            'Custom workflow automation',
            'Integration with 50+ tools'
        ],
        technologies: ['React', 'Node.js', 'AI/ML', 'WebSocket'],
        pricingType: 'monthly',
        freeTrialDays: 14,
        demoUrl: '#'
    },
    {
        id: 2,
        name: 'DataViz Analytics',
        category: 'analytics',
        description: 'Comprehensive business intelligence platform with real-time data visualization and predictive analytics.',
        image: 'https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 199.99,
        originalPrice: null,
        rating: 4.9,
        downloads: '15K+',
        features: [
            'Real-time data visualization',
            'Predictive analytics engine',
            'Custom dashboard builder',
            'Multi-source data integration',
            'Advanced reporting tools'
        ],
        technologies: ['React', 'D3.js', 'Python', 'Machine Learning'],
        pricingType: 'one-time',
        freeTrialDays: 7,
        demoUrl: '#'
    },
    {
        id: 3,
        name: 'ShopMaster Suite',
        category: 'ecommerce',
        description: 'Complete e-commerce solution with inventory management, payment processing, and customer analytics.',
        image: 'https://images.pexels.com/photos/230544/pexels-photo-230544.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 89.99,
        originalPrice: 129.99,
        rating: 4.7,
        downloads: '30K+',
        features: [
            'Multi-channel inventory management',
            'Integrated payment processing',
            'Customer behavior analytics',
            'Automated marketing tools',
            'Mobile-responsive storefront'
        ],
        technologies: ['Next.js', 'Stripe', 'PostgreSQL', 'Redis'],
        pricingType: 'monthly',
        freeTrialDays: 30,
        demoUrl: '#'
    },
    {
        id: 4,
        name: 'HealthTracker Pro',
        category: 'healthcare',
        description: 'Comprehensive health monitoring platform with patient management and telemedicine capabilities.',
        image: 'https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 299.99,
        originalPrice: null,
        rating: 4.9,
        downloads: '8K+',
        features: [
            'Patient record management',
            'Telemedicine integration',
            'Health analytics dashboard',
            'Appointment scheduling',
            'HIPAA compliant security'
        ],
        technologies: ['React', 'Node.js', 'WebRTC', 'Encryption'],
        pricingType: 'one-time',
        freeTrialDays: 14,
        demoUrl: '#'
    },
    {
        id: 5,
        name: 'FinanceFlow',
        category: 'finance',
        description: 'Personal and business finance management with AI-powered insights and automated reporting.',
        image: 'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 39.99,
        originalPrice: 59.99,
        rating: 4.6,
        downloads: '20K+',
        features: [
            'Automated expense tracking',
            'AI-powered financial insights',
            'Multi-account management',
            'Custom budget planning',
            'Tax preparation tools'
        ],
        technologies: ['React Native', 'AI/ML', 'Blockchain', 'Security'],
        pricingType: 'monthly',
        freeTrialDays: 21,
        demoUrl: '#'
    },
    {
        id: 6,
        name: 'LearnHub Platform',
        category: 'education',
        description: 'Interactive e-learning platform with course creation tools and student progress tracking.',
        image: 'https://images.pexels.com/photos/3184298/pexels-photo-3184298.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 149.99,
        originalPrice: null,
        rating: 4.8,
        downloads: '12K+',
        features: [
            'Interactive course builder',
            'Student progress analytics',
            'Video streaming platform',
            'Assessment and quiz tools',
            'Certificate generation'
        ],
        technologies: ['Vue.js', 'Node.js', 'Video Streaming', 'Analytics'],
        pricingType: 'one-time',
        freeTrialDays: 14,
        demoUrl: '#'
    },
    {
        id: 7,
        name: 'CRM Master',
        category: 'productivity',
        description: 'Advanced customer relationship management system with sales automation and lead tracking.',
        image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 69.99,
        originalPrice: 99.99,
        rating: 4.7,
        downloads: '18K+',
        features: [
            'Lead management system',
            'Sales pipeline automation',
            'Customer communication tools',
            'Performance analytics',
            'Integration with email platforms'
        ],
        technologies: ['Angular', 'Spring Boot', 'PostgreSQL', 'Email APIs'],
        pricingType: 'monthly',
        freeTrialDays: 14,
        demoUrl: '#'
    },
    {
        id: 8,
        name: 'Inventory Pro',
        category: 'productivity',
        description: 'Smart inventory management system with predictive analytics and automated reordering.',
        image: 'https://images.pexels.com/photos/906494/pexels-photo-906494.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 79.99,
        originalPrice: null,
        rating: 4.8,
        downloads: '22K+',
        features: [
            'Real-time inventory tracking',
            'Predictive reorder alerts',
            'Multi-location management',
            'Barcode scanning support',
            'Supplier management tools'
        ],
        technologies: ['React', 'Python', 'Machine Learning', 'IoT'],
        pricingType: 'monthly',
        freeTrialDays: 30,
        demoUrl: '#'
    },
    {
        id: 9,
        name: 'Social Analytics Pro',
        category: 'analytics',
        description: 'Comprehensive social media analytics platform with sentiment analysis and trend prediction.',
        image: 'https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 129.99,
        originalPrice: 179.99,
        rating: 4.6,
        downloads: '10K+',
        features: [
            'Multi-platform social monitoring',
            'Sentiment analysis engine',
            'Trend prediction algorithms',
            'Competitor analysis tools',
            'Automated reporting'
        ],
        technologies: ['Python', 'NLP', 'Machine Learning', 'APIs'],
        pricingType: 'monthly',
        freeTrialDays: 7,
        demoUrl: '#'
    },
    {
        id: 10,
        name: 'WebStore Builder',
        category: 'ecommerce',
        description: 'Drag-and-drop e-commerce website builder with integrated payment and shipping solutions.',
        image: 'https://images.pexels.com/photos/230544/pexels-photo-230544.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 59.99,
        originalPrice: 89.99,
        rating: 4.5,
        downloads: '35K+',
        features: [
            'Drag-and-drop website builder',
            'Integrated payment gateways',
            'Shipping calculator',
            'SEO optimization tools',
            'Mobile-responsive themes'
        ],
        technologies: ['React', 'Stripe', 'PayPal', 'SEO Tools'],
        pricingType: 'monthly',
        freeTrialDays: 14,
        demoUrl: '#'
    },
    {
        id: 11,
        name: 'Time Tracker Elite',
        category: 'productivity',
        description: 'Advanced time tracking and productivity analysis tool for teams and freelancers.',
        image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 29.99,
        originalPrice: 49.99,
        rating: 4.7,
        downloads: '28K+',
        features: [
            'Automatic time tracking',
            'Productivity analytics',
            'Project time allocation',
            'Team performance metrics',
            'Invoice generation'
        ],
        technologies: ['Electron', 'React', 'Node.js', 'Analytics'],
        pricingType: 'monthly',
        freeTrialDays: 14,
        demoUrl: '#'
    },
    {
        id: 12,
        name: 'Market Research Hub',
        category: 'analytics',
        description: 'Comprehensive market research platform with survey tools and data analysis capabilities.',
        image: 'https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 179.99,
        originalPrice: null,
        rating: 4.8,
        downloads: '6K+',
        features: [
            'Survey creation tools',
            'Statistical analysis engine',
            'Market trend visualization',
            'Competitor benchmarking',
            'Custom report generation'
        ],
        technologies: ['Vue.js', 'Python', 'Statistics', 'Data Visualization'],
        pricingType: 'one-time',
        freeTrialDays: 14,
        demoUrl: '#'
    },
    {
        id: 13,
        name: 'Marketplace Connect',
        category: 'ecommerce',
        description: 'Multi-marketplace integration platform for managing products across different e-commerce channels.',
        image: 'https://images.pexels.com/photos/230544/pexels-photo-230544.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 99.99,
        originalPrice: 149.99,
        rating: 4.6,
        downloads: '14K+',
        features: [
            'Multi-marketplace sync',
            'Centralized inventory management',
            'Automated pricing updates',
            'Order management system',
            'Performance analytics'
        ],
        technologies: ['Node.js', 'APIs', 'Database Sync', 'Automation'],
        pricingType: 'monthly',
        freeTrialDays: 21,
        demoUrl: '#'
    },
    {
        id: 14,
        name: 'MedRecord System',
        category: 'healthcare',
        description: 'Electronic health record system with patient portal and clinical decision support.',
        image: 'https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 399.99,
        originalPrice: null,
        rating: 4.9,
        downloads: '5K+',
        features: [
            'Electronic health records',
            'Patient portal access',
            'Clinical decision support',
            'Prescription management',
            'Medical imaging integration'
        ],
        technologies: ['React', 'FHIR', 'HL7', 'Security', 'Compliance'],
        pricingType: 'one-time',
        freeTrialDays: 30,
        demoUrl: '#'
    },
    {
        id: 15,
        name: 'CryptoTrader Pro',
        category: 'finance',
        description: 'Advanced cryptocurrency trading platform with AI-powered market analysis and automated trading.',
        image: 'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=800',
        price: 199.99,
        originalPrice: 299.99,
        rating: 4.5,
        downloads: '9K+',
        features: [
            'AI-powered market analysis',
            'Automated trading bots',
            'Portfolio management',
            'Risk assessment tools',
            'Real-time market data'
        ],
        technologies: ['React', 'AI/ML', 'Blockchain', 'WebSocket', 'Security'],
        pricingType: 'monthly',
        freeTrialDays: 7,
        demoUrl: '#'
    }
];